### ISSUE TITLE
Idea: Adding Black module to keep consistent code format

### ISSUE THREAD

**Issue by Domejko** [alat-rights/alana-utilities#12]
[Black](https://pypi.org/project/black/) formatter can be add to keep consistent code format with one simple command `black ./` .

If you like the idea you can assignee this to me and tomorrow I will send PR with formatted code and updated `install_requires` in **setup.py**.

**Comment by alat-rights** [comment]
I don't find Black code very readable, and the repo is small enough currently that I don't find this super compelling.

We can revisit this in the future :)
