### ISSUE TITLE
Code cleanup/formating

### ISSUE THREAD

**Issue by Domejko** [alat-rights/alana-utilities#14]
I would suggest proper formatting the code according to PEP guidelines because even on 2K ultra-wide screen I have difficulties in reaching some parts of code that are 3 pages wide.

As you rejected idea of using Black formatter I can attempt to adjust it manually since it's not much of a code (but in present format hard to work with). 
Unless you know some different formatting package which we could use.

**Comment by alat-rights** [comment]
Ok, if this is affecting dev ergonomics for you, I'm happy to use Black.

**Comment by Domejko** [comment]
It really helps in code readability. As comes to Black I'm also not a big fan on `C` style formatting but still it's more readable. We could also take a look on other formatters available on PyPI.

As comes to CI you will want to have it all in one file or create separate for style/testing ?

**Comment by alat-rights** [comment]
Maybe a single new `.yml` file for Black in .github/workflows ? Feel free to iterate/experiment.

Thanks for taking this on! Btw: How did you find this repo?

**Comment by Domejko** [comment]
I will start working on that so you can assign this issue on me.

No problem. I was searching for fresh repo with active maintainer and pending issues to which I could contribute and I found yours.
