### ISSUE TITLE
Flaky not included in requirements 

### ISSUE THREAD

**Issue by Domejko** [alat-rights/alana-utilities#16]
Flaky which is needed for testing was not included in **setup.py** `install_requires`.

**Comment by alat-rights** [comment]
This is not required for end-users, so I don’t think should be in requires.

Rationale: I’d like the pip install to run quickly for people who do it in
e.g. a Google Colab, so I’m very skeptical of adding new requirements,
unless it breaks the API.

**Comment by Domejko** [comment]
Yes but it's required for testing so if you don't want to add additional requirement then let's update `README.md` that `pip install flaky` is needed for testing pursues.

**Comment by alat-rights** [comment]
Ok I agree :)

**Comment by Domejko** [comment]
Cool, at the moment I'm working on writing local tests so when I'll stop that gonna update `README.md`, remove `flaky` from **setup.py** and push changes to PR.

**Comment by alat-rights** [comment]
Cool, thanks for the heads up!

Looking forward to your PR :)
