### ISSUE TITLE
Cleanup: Move alias functions to separate file (`alias.py`?)

### ISSUE THREAD

**Issue by alat-rights** [alat-rights/alana-utilities#8]
Motivation: We want to clean up documentation here https://utils.alana.computer/prompt/

**Comment by Domejko** [comment]
Hi @alat-rights 

I will take care of this one.

**Comment by alat-rights** [comment]
Cool! Excited to see your PR :)

**Comment by alat-rights** [comment]
Thanks @Domejko !
